export const verses = [
  { text: "I can do all things through Christ which strengtheneth me.", reference: "Philippians 4:13" },
  { text: "The LORD is my shepherd; I shall not want.", reference: "Psalm 23:1" },
  { text: "Trust in the LORD with all thine heart; and lean not unto thine own understanding.", reference: "Proverbs 3:5" },
  { text: "For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.", reference: "John 3:16" },
  { text: "Be strong and of a good courage; be not afraid, neither be thou dismayed: for the LORD thy God is with thee whithersoever thou goest.", reference: "Joshua 1:9" },
  { text: "For I know the thoughts that I think toward you, saith the LORD, thoughts of peace, and not of evil, to give you an expected end.", reference: "Jeremiah 29:11" },
  { text: "The LORD is my light and my salvation; whom shall I fear?", reference: "Psalm 27:1" },
  { text: "Come unto me, all ye that labour and are heavy laden, and I will give you rest.", reference: "Matthew 11:28" },
  { text: "And we know that all things work together for good to them that love God.", reference: "Romans 8:28" },
  { text: "Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God.", reference: "Philippians 4:6" },
  { text: "The LORD shall fight for you, and ye shall hold your peace.", reference: "Exodus 14:14" },
  { text: "But they that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles.", reference: "Isaiah 40:31" },
  { text: "God is our refuge and strength, a very present help in trouble.", reference: "Psalm 46:1" },
  { text: "Casting all your care upon him; for he careth for you.", reference: "1 Peter 5:7" },
  { text: "The name of the LORD is a strong tower: the righteous runneth into it, and is safe.", reference: "Proverbs 18:10" },
  { text: "Fear thou not; for I am with thee: be not dismayed; for I am thy God.", reference: "Isaiah 41:10" },
  { text: "Yea, though I walk through the valley of the shadow of death, I will fear no evil: for thou art with me.", reference: "Psalm 23:4" },
  { text: "Delight thyself also in the LORD; and he shall give thee the desires of thine heart.", reference: "Psalm 37:4" },
  { text: "It is of the LORD'S mercies that we are not consumed, because his compassions fail not.", reference: "Lamentations 3:22" },
  { text: "But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you.", reference: "Matthew 6:33" },
  { text: "No weapon that is formed against thee shall prosper.", reference: "Isaiah 54:17" },
  { text: "The LORD thy God in the midst of thee is mighty; he will save, he will rejoice over thee with joy.", reference: "Zephaniah 3:17" },
  { text: "For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.", reference: "2 Timothy 1:7" },
  { text: "Create in me a clean heart, O God; and renew a right spirit within me.", reference: "Psalm 51:10" },
  { text: "He healeth the broken in heart, and bindeth up their wounds.", reference: "Psalm 147:3" },
  { text: "The LORD is nigh unto them that are of a broken heart; and saveth such as be of a contrite spirit.", reference: "Psalm 34:18" },
  { text: "In all thy ways acknowledge him, and he shall direct thy paths.", reference: "Proverbs 3:6" },
  { text: "For with God nothing shall be impossible.", reference: "Luke 1:37" },
  { text: "Jesus saith unto him, I am the way, the truth, and the life.", reference: "John 14:6" },
  { text: "Greater is he that is in you, than he that is in the world.", reference: "1 John 4:4" },
  { text: "Be still, and know that I am God.", reference: "Psalm 46:10" },
  { text: "For the joy of the LORD is your strength.", reference: "Nehemiah 8:10" },
  { text: "With God all things are possible.", reference: "Matthew 19:26" },
  { text: "And blessed is she that believed: for there shall be a performance of those things which were told her from the Lord.", reference: "Luke 1:45" },
  { text: "But my God shall supply all your need according to his riches in glory by Christ Jesus.", reference: "Philippians 4:19" },
  { text: "A man's heart deviseth his way: but the LORD directeth his steps.", reference: "Proverbs 16:9" },
  { text: "O give thanks unto the LORD, for he is good: for his mercy endureth for ever.", reference: "Psalm 107:1" },
  { text: "I am crucified with Christ: nevertheless I live; yet not I, but Christ liveth in me.", reference: "Galatians 2:20" },
  { text: "This is the day which the LORD hath made; we will rejoice and be glad in it.", reference: "Psalm 118:24" },
  { text: "O taste and see that the LORD is good: blessed is the man that trusteth in him.", reference: "Psalm 34:8" },
  { text: "My grace is sufficient for thee: for my strength is made perfect in weakness.", reference: "2 Corinthians 12:9" },
  { text: "Wait on the LORD: be of good courage, and he shall strengthen thine heart.", reference: "Psalm 27:14" },
  { text: "Ask, and it shall be given you; seek, and ye shall find; knock, and it shall be opened unto you.", reference: "Matthew 7:7" },
  { text: "The LORD bless thee, and keep thee: The LORD make his face shine upon thee.", reference: "Numbers 6:24-25" },
  { text: "I will praise thee; for I am fearfully and wonderfully made.", reference: "Psalm 139:14" },
  { text: "If God be for us, who can be against us?", reference: "Romans 8:31" },
  { text: "And let us not be weary in well doing: for in due season we shall reap, if we faint not.", reference: "Galatians 6:9" },
  { text: "Thy word is a lamp unto my feet, and a light unto my path.", reference: "Psalm 119:105" },
  { text: "Commit thy way unto the LORD; trust also in him; and he shall bring it to pass.", reference: "Psalm 37:5" },
  { text: "The LORD is good unto them that wait for him, to the soul that seeketh him.", reference: "Lamentations 3:25" },
  { text: "He giveth power to the faint; and to them that have no might he increaseth strength.", reference: "Isaiah 40:29" },
  { text: "For where two or three are gathered together in my name, there am I in the midst of them.", reference: "Matthew 18:20" },
  { text: "Blessed are the pure in heart: for they shall see God.", reference: "Matthew 5:8" },
  { text: "But the Lord is faithful, who shall stablish you, and keep you from evil.", reference: "2 Thessalonians 3:3" },
  { text: "Peace I leave with you, my peace I give unto you.", reference: "John 14:27" },
  { text: "I am the vine, ye are the branches: He that abideth in me, and I in him, the same bringeth forth much fruit.", reference: "John 15:5" },
  { text: "And the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus.", reference: "Philippians 4:7" },
  { text: "He that dwelleth in the secret place of the most High shall abide under the shadow of the Almighty.", reference: "Psalm 91:1" },
  { text: "The LORD is my rock, and my fortress, and my deliverer.", reference: "Psalm 18:2" },
  { text: "Blessed are they which do hunger and thirst after righteousness: for they shall be filled.", reference: "Matthew 5:6" },
  { text: "Be not overcome of evil, but overcome evil with good.", reference: "Romans 12:21" },
  { text: "Charity suffereth long, and is kind; charity envieth not; charity vaunteth not itself, is not puffed up.", reference: "1 Corinthians 13:4" },
  { text: "For by grace are ye saved through faith; and that not of yourselves: it is the gift of God.", reference: "Ephesians 2:8" },
  { text: "Put on the whole armour of God, that ye may be able to stand against the wiles of the devil.", reference: "Ephesians 6:11" },
  { text: "I will lift up mine eyes unto the hills, from whence cometh my help. My help cometh from the LORD.", reference: "Psalm 121:1-2" },
  { text: "Wherefore God also hath highly exalted him, and given him a name which is above every name.", reference: "Philippians 2:9" },
  { text: "He that believeth on me, as the scripture hath said, out of his belly shall flow rivers of living water.", reference: "John 7:38" },
  { text: "Ye are the light of the world. A city that is set on an hill cannot be hid.", reference: "Matthew 5:14" },
  { text: "For we walk by faith, not by sight.", reference: "2 Corinthians 5:7" },
  { text: "Now faith is the substance of things hoped for, the evidence of things not seen.", reference: "Hebrews 11:1" },
  { text: "Be not conformed to this world: but be ye transformed by the renewing of your mind.", reference: "Romans 12:2" },
  { text: "Let your light so shine before men, that they may see your good works, and glorify your Father which is in heaven.", reference: "Matthew 5:16" },
  { text: "I sought the LORD, and he heard me, and delivered me from all my fears.", reference: "Psalm 34:4" },
  { text: "Blessed is the man that trusteth in the LORD, and whose hope the LORD is.", reference: "Jeremiah 17:7" },
  { text: "Being confident of this very thing, that he which hath begun a good work in you will perform it until the day of Jesus Christ.", reference: "Philippians 1:6" },
  { text: "And the LORD shall guide thee continually, and satisfy thy soul in drought.", reference: "Isaiah 58:11" },
  { text: "Rejoice evermore. Pray without ceasing. In every thing give thanks.", reference: "1 Thessalonians 5:16-18" },
  { text: "Draw nigh to God, and he will draw nigh to you.", reference: "James 4:8" },
  { text: "The steps of a good man are ordered by the LORD: and he delighteth in his way.", reference: "Psalm 37:23" },
  { text: "Thou wilt keep him in perfect peace, whose mind is stayed on thee: because he trusteth in thee.", reference: "Isaiah 26:3" },
  { text: "For whatsoever is born of God overcometh the world.", reference: "1 John 5:4" },
  { text: "The LORD is my strength and song, and he is become my salvation.", reference: "Exodus 15:2" },
  { text: "Blessed are the merciful: for they shall obtain mercy.", reference: "Matthew 5:7" },
  { text: "For the LORD God is a sun and shield: the LORD will give grace and glory.", reference: "Psalm 84:11" },
  { text: "I will never leave thee, nor forsake thee.", reference: "Hebrews 13:5" },
  { text: "The earth is the LORD'S, and the fulness thereof; the world, and they that dwell therein.", reference: "Psalm 24:1" },
  { text: "Bless the LORD, O my soul, and forget not all his benefits.", reference: "Psalm 103:2" },
  { text: "Let every thing that hath breath praise the LORD. Praise ye the LORD.", reference: "Psalm 150:6" },
  { text: "They that trust in the LORD shall be as mount Zion, which cannot be removed.", reference: "Psalm 125:1" },
  { text: "The LORD will perfect that which concerneth me.", reference: "Psalm 138:8" },
  { text: "But God commendeth his love toward us, in that, while we were yet sinners, Christ died for us.", reference: "Romans 5:8" },
  { text: "Jesus said unto her, I am the resurrection, and the life: he that believeth in me, though he were dead, yet shall he live.", reference: "John 11:25" },
  { text: "The thief cometh not, but for to steal, and to kill, and to destroy: I am come that they might have life, and that they might have it more abundantly.", reference: "John 10:10" },
  { text: "Surely goodness and mercy shall follow me all the days of my life.", reference: "Psalm 23:6" },
  { text: "For God is not unrighteous to forget your work and labour of love, which ye have shewed toward his name.", reference: "Hebrews 6:10" },
  { text: "For I am persuaded, that neither death, nor life, nor angels, nor principalities, nor powers, shall be able to separate us from the love of God.", reference: "Romans 8:38-39" },
  { text: "And they overcame him by the blood of the Lamb, and by the word of their testimony.", reference: "Revelation 12:11" },
  { text: "The Lord is not slack concerning his promise, as some men count slackness.", reference: "2 Peter 3:9" },
  { text: "Now the God of hope fill you with all joy and peace in believing.", reference: "Romans 15:13" },
   { text: "The LORD is my portion, saith my soul; therefore will I hope in him.", reference: "Lamentations 3:24" },
  { text: "Blessed is the nation whose God is the LORD.", reference: "Psalm 33:12" },
  { text: "The effectual fervent prayer of a righteous man availeth much.", reference: "James 5:16" },
  { text: "Thy righteousness is like the great mountains; thy judgments are a great deep.", reference: "Psalm 36:6" },
  { text: "The LORD upholdeth all that fall, and raiseth up all those that be bowed down.", reference: "Psalm 145:14" },
  { text: "I have set the LORD always before me: because he is at my right hand, I shall not be moved.", reference: "Psalm 16:8" },
  { text: "O LORD, thou art my God; I will exalt thee, I will praise thy name.", reference: "Isaiah 25:1" },
  { text: "The LORD is good; his mercy is everlasting; and his truth endureth to all generations.", reference: "Psalm 100:5" },
  { text: "He shall cover thee with his feathers, and under his wings shalt thou trust.", reference: "Psalm 91:4" },
  { text: "For thou, LORD, art good, and ready to forgive; and plenteous in mercy unto all them that call upon thee.", reference: "Psalm 86:5" },
  { text: "Have not I commanded thee? Be strong and of a good courage; be not afraid.", reference: "Joshua 1:9" },
  { text: "Thou art my hiding place; thou shalt preserve me from trouble.", reference: "Psalm 32:7" },
  { text: "The LORD shall preserve thy going out and thy coming in from this time forth.", reference: "Psalm 121:8" },
  { text: "For the LORD loveth judgment, and forsaketh not his saints; they are preserved for ever.", reference: "Psalm 37:28" },
  { text: "Blessed are they that mourn: for they shall be comforted.", reference: "Matthew 5:4" },
  { text: "Blessed are the peacemakers: for they shall be called the children of God.", reference: "Matthew 5:9" },
  { text: "But as many as received him, to them gave he power to become the sons of God.", reference: "John 1:12" },
  { text: "Verily, verily, I say unto you, He that heareth my word, and believeth on him that sent me, hath everlasting life.", reference: "John 5:24" },
  { text: "And ye shall know the truth, and the truth shall make you free.", reference: "John 8:32" },
  { text: "I am the good shepherd: the good shepherd giveth his life for the sheep.", reference: "John 10:11" },
  { text: "Let not your heart be troubled: ye believe in God, believe also in me.", reference: "John 14:1" },
  { text: "If ye shall ask any thing in my name, I will do it.", reference: "John 14:14" },
  { text: "Ye have not chosen me, but I have chosen you, and ordained you, that ye should go and bring forth fruit.", reference: "John 15:16" },
  { text: "These things I have spoken unto you, that in me ye might have peace.", reference: "John 16:33" },
  { text: "Sanctify them through thy truth: thy word is truth.", reference: "John 17:17" },
  { text: "Therefore being justified by faith, we have peace with God through our Lord Jesus Christ.", reference: "Romans 5:1" },
  { text: "There is therefore now no condemnation to them which are in Christ Jesus.", reference: "Romans 8:1" },
  { text: "For the wages of sin is death; but the gift of God is eternal life through Jesus Christ our Lord.", reference: "Romans 6:23" },
  { text: "That if thou shalt confess with thy mouth the Lord Jesus, and shalt believe in thine heart that God hath raised him from the dead, thou shalt be saved.", reference: "Romans 10:9" },
  { text: "For whosoever shall call upon the name of the Lord shall be saved.", reference: "Romans 10:13" },
  { text: "I beseech you therefore, brethren, by the mercies of God, that ye present your bodies a living sacrifice, holy, acceptable unto God.", reference: "Romans 12:1" },
  { text: "Rejoice with them that do rejoice, and weep with them that weep.", reference: "Romans 12:15" },
  { text: "Now the God of patience and consolation grant you to be likeminded one toward another.", reference: "Romans 15:5" },
  { text: "But God hath chosen the foolish things of the world to confound the wise.", reference: "1 Corinthians 1:27" },
  { text: "Eye hath not seen, nor ear heard, neither have entered into the heart of man, the things which God hath prepared for them that love him.", reference: "1 Corinthians 2:9" },
  { text: "Know ye not that ye are the temple of God, and that the Spirit of God dwelleth in you?", reference: "1 Corinthians 3:16" },
  { text: "There hath no temptation taken you but such as is common to man: but God is faithful.", reference: "1 Corinthians 10:13" },
  { text: "And now abideth faith, hope, charity, these three; but the greatest of these is charity.", reference: "1 Corinthians 13:13" },
  { text: "O death, where is thy sting? O grave, where is thy victory?", reference: "1 Corinthians 15:55" },
  { text: "Therefore, my beloved brethren, be ye stedfast, unmoveable, always abounding in the work of the Lord.", reference: "1 Corinthians 15:58" },
  { text: "Now thanks be unto God, which always causeth us to triumph in Christ.", reference: "2 Corinthians 2:14" },
  { text: "For we are unto God a sweet savour of Christ.", reference: "2 Corinthians 2:15" },
  { text: "Therefore if any man be in Christ, he is a new creature: old things are passed away; behold, all things are become new.", reference: "2 Corinthians 5:17" },
  { text: "For he hath made him to be sin for us, who knew no sin; that we might be made the righteousness of God in him.", reference: "2 Corinthians 5:21" },
  { text: "Now he that ministereth seed to the sower both minister bread for your food, and multiply your seed sown.", reference: "2 Corinthians 9:10" },
  { text: "For though we walk in the flesh, we do not war after the flesh.", reference: "2 Corinthians 10:3" },
  { text: "Stand fast therefore in the liberty wherewith Christ hath made us free.", reference: "Galatians 5:1" },
  { text: "But the fruit of the Spirit is love, joy, peace, longsuffering, gentleness, goodness, faith.", reference: "Galatians 5:22" },
  { text: "Be not deceived; God is not mocked: for whatsoever a man soweth, that shall he also reap.", reference: "Galatians 6:7" },
  { text: "According as he hath chosen us in him before the foundation of the world, that we should be holy.", reference: "Ephesians 1:4" },
  { text: "That he would grant you, according to the riches of his glory, to be strengthened with might by his Spirit in the inner man.", reference: "Ephesians 3:16" },
  { text: "Now unto him that is able to do exceeding abundantly above all that we ask or think.", reference: "Ephesians 3:20" },
  { text: "And be ye kind one to another, tenderhearted, forgiving one another, even as God for Christ's sake hath forgiven you.", reference: "Ephesians 4:32" },
  { text: "Be ye therefore followers of God, as dear children.", reference: "Ephesians 5:1" },
  { text: "Finally, my brethren, be strong in the Lord, and in the power of his might.", reference: "Ephesians 6:10" },
  { text: "And the very God of peace sanctify you wholly.", reference: "1 Thessalonians 5:23" },
  { text: "For God hath not appointed us to wrath, but to obtain salvation by our Lord Jesus Christ.", reference: "1 Thessalonians 5:9" },
  { text: "Fight the good fight of faith, lay hold on eternal life.", reference: "1 Timothy 6:12" },
  { text: "All scripture is given by inspiration of God, and is profitable for doctrine, for reproof, for correction, for instruction in righteousness.", reference: "2 Timothy 3:16" },
  { text: "I have fought a good fight, I have finished my course, I have kept the faith.", reference: "2 Timothy 4:7" },
  { text: "Looking unto Jesus the author and finisher of our faith.", reference: "Hebrews 12:2" },
  { text: "Let us hold fast the profession of our faith without wavering; for he is faithful that promised.", reference: "Hebrews 10:23" },
  { text: "If any of you lack wisdom, let him ask of God, that giveth to all men liberally.", reference: "James 1:5" },
  { text: "Submit yourselves therefore to God. Resist the devil, and he will flee from you.", reference: "James 4:7" },
  { text: "Humble yourselves therefore under the mighty hand of God, that he may exalt you in due time.", reference: "1 Peter 5:6" },
  { text: "But ye are a chosen generation, a royal priesthood, an holy nation, a peculiar people.", reference: "1 Peter 2:9" },
  { text: "Beloved, I wish above all things that thou mayest prosper and be in health, even as thy soul prospereth.", reference: "3 John 1:2" },
  { text: "Behold, I stand at the door, and knock: if any man hear my voice, and open the door, I will come in to him.", reference: "Revelation 3:20" },
  { text: "And God shall wipe away all tears from their eyes; and there shall be no more death.", reference: "Revelation 21:4" },
  { text: "He that overcometh shall inherit all things; and I will be his God, and he shall be my son.", reference: "Revelation 21:7" },
  { text: "The LORD is my strength and my shield; my heart trusted in him, and I am helped.", reference: "Psalm 28:7" },
  { text: "Many are the afflictions of the righteous: but the LORD delivereth him out of them all.", reference: "Psalm 34:19" },
  { text: "Cast thy burden upon the LORD, and he shall sustain thee.", reference: "Psalm 55:22" },
  { text: "In God have I put my trust: I will not be afraid what man can do unto me.", reference: "Psalm 56:11" },
  { text: "From the end of the earth will I cry unto thee, when my heart is overwhelmed: lead me to the rock that is higher than I.", reference: "Psalm 61:2" },
  { text: "My soul, wait thou only upon God; for my expectation is from him.", reference: "Psalm 62:5" },
  { text: "Because thy lovingkindness is better than life, my lips shall praise thee.", reference: "Psalm 63:3" },
  { text: "Blessed is the man whose strength is in thee; in whose heart are the ways of them.", reference: "Psalm 84:5" },
  { text: "For a day in thy courts is better than a thousand. I had rather be a doorkeeper in the house of my God.", reference: "Psalm 84:10" },
  { text: "He that goeth forth and weepeth, bearing precious seed, shall doubtless come again with rejoicing.", reference: "Psalm 126:6" },
  { text: "Lo, children are an heritage of the LORD: and the fruit of the womb is his reward.", reference: "Psalm 127:3" },
  { text: "Whither shall I go from thy spirit? or whither shall I flee from thy presence?", reference: "Psalm 139:7" },
  { text: "Search me, O God, and know my heart: try me, and know my thoughts.", reference: "Psalm 139:23" },
  { text: "The LORD is righteous in all his ways, and holy in all his works.", reference: "Psalm 145:17" },
  { text: "Happy is he that hath the God of Jacob for his help, whose hope is in the LORD his God.", reference: "Psalm 146:5" },
  { text: "A wise man will hear, and will increase learning; and a man of understanding shall attain unto wise counsels.", reference: "Proverbs 1:5" },
  { text: "The fear of the LORD is the beginning of wisdom.", reference: "Proverbs 9:10" },
  { text: "A soft answer turneth away wrath: but grievous words stir up anger.", reference: "Proverbs 15:1" },
  { text: "Pride goeth before destruction, and an haughty spirit before a fall.", reference: "Proverbs 16:18" },
  { text: "A merry heart doeth good like a medicine.", reference: "Proverbs 17:22" },
  { text: "Train up a child in the way he should go: and when he is old, he will not depart from it.", reference: "Proverbs 22:6" },
  { text: "Where there is no vision, the people perish.", reference: "Proverbs 29:18" },
  { text: "Who can find a virtuous woman? for her price is far above rubies.", reference: "Proverbs 31:10" },
  { text: "To every thing there is a season, and a time to every purpose under the heaven.", reference: "Ecclesiastes 3:1" },
  { text: "The grass withereth, the flower fadeth: but the word of our God shall stand for ever.", reference: "Isaiah 40:8" },
  { text: "Arise, shine; for thy light is come, and the glory of the LORD is risen upon thee.", reference: "Isaiah 60:1" },
  { text: "The Spirit of the Lord GOD is upon me; because the LORD hath anointed me to preach good tidings unto the meek.", reference: "Isaiah 61:1" },
  { text: "For as the heavens are higher than the earth, so are my ways higher than your ways.", reference: "Isaiah 55:9" },
  {text: "Call unto me, and I will answer thee, and shew thee great and mighty things, which thou knowest not.", reference: "Jeremiah 33:3"}
]

